version: "3.8"

services:
  backend:
    build:
      context: ./backend
    environment:
      DB_URI: mongodb://mongo:27017
      DB_NAME: go_todo
      DB_COLLECTION_NAME: todos
    ports:
      - "9000:9000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
